os: osx
osx_image: xcode10.2
language: node_js
node_js:
- '10'
- '12'
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install: yarn
before_script: sh -c "git log | head -12"
script: yarn run test
deploy:
  provider: npm
  email: npmjs@appcelerator.com
  api_key:
    secure: KXBIiRgIIdsPgrxg0pI7K5gbzkgvUWG4rFaEqBl3a8LPNCukgI54/OTbS4xJCSyzClJnYqc/tRjBtPeHPc9eDiZFJXOGNtbRLGqmPX06thPPmsdm/Ol19qmi2pqGnPMDzZuA6/YI5IRYUP+6Mk4oLcht2BMpeuPLavqnXbsTpDM=
  on:
    tags: true
    repo: appcelerator/node-ios-device
